# Generated by Django 2.0 on 2018-01-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180129_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra',
            field=models.TextField(blank=True),
        ),
    ]
