# Generated by Django 2.0 on 2018-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20180115_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
