# Generated by Django 2.0 on 2018-01-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20180126_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'quizzes'},
        ),
    ]
