# Generated by Django 2.0 on 2018-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20180129_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions_per_page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionsubmission',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
