# Generated by Django 2.0 on 2018-02-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20180207_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pass_score',
            field=models.FloatField(default=0),
        ),
    ]
