# Generated by Django 2.0.2 on 2018-02-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20180225_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsubmission',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='scoredistribution',
            options={'ordering': ['-id']},
        ),
    ]
