# Generated by Django 2.0.2 on 2018-02-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_auto_20180225_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scoredistribution',
            options={'ordering': ['-created_at']},
        ),
    ]
