# Generated by Django 2.0 on 2018-01-15 13:12

from django.db import migrations, models
import quizsys.apps.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180114_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10, unique=True, validators=[quizsys.apps.users.validators.validate_no_space]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[quizsys.apps.users.validators.validate_no_space]),
        ),
    ]
